Query:
    type: object
    config:
        description: "Main query"
        fields:
            greeting:
                type: String!
                resolve: '@=resolver("App\\GraphQL\\Resolver\\GreetingResolver::sayHello")'
