Query:
    type: object
    config:
        description: "Main query"
        fields:
            greeting:
                type: String!
                args:
                    name:
                        type: String!
                        description: 'User name'
                resolve: '@=resolver("App\\GraphQL\\Resolver\\GreetingResolver::sayHello", [args["name"]])'
